services:
  users:
    image: smartpad/money-minder:users
    ports:
      - "18082:18082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-users:5432/moneyminder-users
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      - postgres-users

  expenses:
    image: smartpad/money-minder:expenses
    ports:
      - "18081:18081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-expenses:5432/moneyminder-expenses
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      - postgres-expenses
      - users

  gateway:
    image: smartpad/money-minder:gateway
    ports:
      - "18080:18080"
    depends_on:
      - users
      - expenses

  frontend:
    image: smartpad/money-minder:front
    ports:
      - "8180:80"
    depends_on:
      - gateway
