services:
  postgres-users:
    image: postgres:15
    environment:
      POSTGRES_DB: moneyminder-users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5433:5432"

  postgres-expenses:
    image: postgres:15
    environment:
      POSTGRES_DB: moneyminder-expenses
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5434:5432"

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "9090:8080"
    depends_on:
      - postgres-users
      - postgres-expenses
