services:
  users:
    build: ./moneyMinder-users
    ports:
      - "18082:18082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-users:5432/moneyminder-users
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      - postgres-users

  expenses:
    build: ./moneyMinder-expenses
    ports:
      - "18081:18081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-expenses:5432/moneyminder-expenses
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      - postgres-expenses
      - users

  gateway:
    build: ./moneyMinder-gateway
    ports:
      - "18080:18080"
    depends_on:
      - users
      - expenses

  frontend:
    build:
      context: ./moneyMinder-front
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./moneyMinder-front:/app
      - /app/node_modules
    depends_on:
      - gateway
